Repository HSD06040/2D_Roguelike, pull requests merged in 2025-07, with the labels that each got.

#94 Feat/boss
  Assets/Animation/Boss/1/AC_Boss1.controller
  Assets/Scripts/EntityFX.cs
  Assets/Scripts/Monster/Monster.cs
  Assets/Scripts/Projectile/ViolinProjectile.cs
  Assets/Student/HSD/Prefabs/BossCirclePattern.prefab
  Assets/Student/HSD/Prefabs/Projectile_Boss1.prefab
  Assets/Student/HSD/Prefabs/Projectile_Boss1.prefab.meta
  Assets/Student/HSD/Scripts/Boss/Boss1/BossBaseState.cs
  Assets/Student/HSD/Scripts/Boss/Boss1/BossFSM_1.cs
  Assets/Student/HSD/Scripts/Boss/Boss1/BossIdleState_1.cs
  Assets/Student/HSD/Scripts/Boss/Boss1/BossMonsterFSM.cs
  Assets/Student/HSD/Scripts/Boss/Boss1/BossStateMachine.cs
  Assets/Student/HSD/Scripts/Boss/Boss1/Pattern/BossCrossPattern.cs
  Assets/Student/HSD/Scripts/Boss/Boss1/Pattern/BossPatternController_1.cs
  Assets/Student/HSD/Scripts/Boss/BossCircleSpawnPattern.cs
  Assets/Student/HSD/Scripts/Boss/BossCircleSpawnPattern.cs.meta
  Assets/Student/HSD/Scripts/Boss/BossPattern.cs
  Assets/Student/HSD/Scripts/Boss/BossPatternObject.cs
  Assets/Student/HSD/Scripts/Boss/EnemySpawnPattern.cs
  Assets/Student/HSD/Scripts/Boss/EnemySpawnPattern.cs.meta
  Assets/Student/HSD/Scripts/Boss/Pattern1.cs
  Assets/Student/HSD/Scripts/Boss/Pattern2.cs
  Assets/Student/HSD/Stage1_3 Test.unity
  Assets/Student/HSD/Stage3_3 Test.unity
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Merge, Feat

#95 Feat/dialogue manager
  Assets/Data/WeaponData/Flute.asset.meta
  Assets/Student/JWJ/Scenes/JWJ_TestScene.unity
  Assets/Student/JWJ/Scripts/DialogueManager.cs
  Assets/Student/JWJ/Scripts/OpeninDialogue.cs
  Assets/Student/JWJ/Scripts/OpeninDialogue.cs.meta
  Assets/Student/JWJ/Scripts/StartDialogue.cs
  Assets/Student/JWJ/Scripts/StartDialogue.cs.meta
Labels: Merge, Feat

#98 Feat/chest portal effect
  Assets/Prefabs/Map/Box_Green.prefab
  Assets/Prefabs/Map/Box_Green.prefab.meta
  Assets/Prefabs/Map/Box_Red.prefab
  Assets/Prefabs/Map/Box_Red.prefab.meta
  Assets/Prefabs/Map/Portal_Stage1.prefab
  Assets/Prefabs/Map/Portal_Stage1.prefab.meta
  Assets/Prefabs/Map/Portal_Stage2.prefab
  Assets/Prefabs/Map/Portal_Stage2.prefab.meta
  Assets/Prefabs/Map/Portal_Stage3.prefab
  Assets/Prefabs/Map/Portal_Stage3.prefab.meta
  Assets/Scripts/Interactable/Box/Box.cs
  Assets/Scripts/Interactable/Box/BoxUI/BoxUIiIn.anim
  Assets/Scripts/Interactable/Box/BoxUI/BoxUiOut.anim
  Assets/Scripts/Interactable/Box/GreenBox.meta
  Assets/Scripts/Interactable/Box/GreenBox/gBox Animator.controller
  Assets/Scripts/Interactable/Box/GreenBox/gBox Animator.controller.meta
  Assets/Scripts/Interactable/Box/GreenBox/gBoxClosed.anim
  Assets/Scripts/Interactable/Box/GreenBox/gBoxClosed.anim.meta
  Assets/Scripts/Interactable/Box/GreenBox/gBoxOpen.anim
  Assets/Scripts/Interactable/Box/GreenBox/gBoxOpen.anim.meta
  Assets/Scripts/Interactable/Box/RedBox.meta
  Assets/Scripts/Interactable/Box/RedBox/rBox Animator.controller
  Assets/Scripts/Interactable/Box/RedBox/rBox Animator.controller.meta
  Assets/Scripts/Interactable/Box/RedBox/rBoxClosed.anim
  Assets/Scripts/Interactable/Box/RedBox/rBoxClosed.anim.meta
  Assets/Scripts/Interactable/Box/RedBox/rBoxOpen.anim
  Assets/Scripts/Interactable/Box/RedBox/rBoxOpen.anim.meta
  Assets/Scripts/MonsterSpawner/MonsterSpawnTrigger.cs
  Assets/Student/JWJ/Prefabs/BoxRewardUI.prefab
  Assets/Student/JWJ/Prefabs/BoxRewardUI.prefab.meta
  Assets/Student/JWJ/Prefabs/DialogueUI.prefab
  Assets/Student/JWJ/Prefabs/DialogueUI.prefab.meta
  Assets/Student/JWJ/Prefabs/HeartUI.prefab
  Assets/Student/JWJ/Prefabs/HeartUI.prefab.meta
  Assets/Student/JWJ/Prefabs/Rooms.prefab
  Assets/Student/JWJ/Prefabs/Rooms.prefab.meta
  Assets/Student/JWJ/Scenes/JWJ_TestScene.unity
  Assets/Student/JWJ/Scripts/ChestApear.cs
  Assets/Student/JWJ/Scripts/ChestApear.cs.meta
Labels: Merge, Feat

#99 Feat/boss
  Assets/Animation/Boss/3.meta
  Assets/Animation/Boss/3/AC_Tobeben.controller
  Assets/Animation/Boss/3/AC_Tobeben.controller.meta
  Assets/Animation/Boss/3/Idle.anim
  Assets/Animation/Boss/3/Idle.anim.meta
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Manager/UI_Manager.cs
  Assets/Student/HSD/11.unity
  Assets/Student/HSD/Prefabs/Piano.meta
  Assets/Student/HSD/Prefabs/Piano/PianoBlack.prefab
  Assets/Student/HSD/Prefabs/Piano/PianoBlack.prefab.meta
  Assets/Student/HSD/Prefabs/Piano/PianoWhiteLeft.prefab
  Assets/Student/HSD/Prefabs/Piano/PianoWhiteLeft.prefab.meta
  Assets/Student/HSD/Prefabs/Piano/PianoWhiteMiddle.prefab
  Assets/Student/HSD/Prefabs/Piano/PianoWhiteMiddle.prefab.meta
  Assets/Student/HSD/Prefabs/Piano/PianoWhiteRigth.prefab
  Assets/Student/HSD/Prefabs/Piano/PianoWhiteRigth.prefab.meta
  Assets/Student/HSD/Scripts/Boss/BossPatternController_3.cs
  Assets/Student/HSD/Scripts/Boss/BossPatternController_3.cs.meta
  Assets/Student/HSD/Scripts/Boss/BossPatternObject.cs
  Assets/Student/HSD/Scripts/UI/FadeScreen.cs
  Assets/Student/HSD/Scripts/UI/FadeScreen.cs.meta
  Assets/Student/HSD/Stage3_3 Test.unity
Labels: Edit, Merge, Feat

#103 [Feat] 아이템 데이터 추가
  Assets/Data/Acc.meta
  Assets/Data/Acc/Effect.meta
  Assets/Data/Acc/Item.meta
  Assets/Data/New Condition Passive Effect.asset
  Assets/Prefabs/FX/EffectObj/OrbitObj.prefab
  Assets/Scripts/Item/Accessories/Accessories.cs
  Assets/Student/HSD/11.unity
  Assets/Student/HSD/AC_Orbit.controller
  Assets/Student/HSD/AC_Orbit.controller.meta
  Assets/Student/HSD/Ac.asset
  Assets/Student/HSD/Ac.asset.meta
  Assets/Student/HSD/Accessories.asset
  Assets/Student/HSD/Accessories.asset.meta
  Assets/Student/HSD/Idle.anim
  Assets/Student/HSD/Idle.anim.meta
  Assets/Student/HSD/Scripts/UseItem/UseItem.cs
  Assets/Student/HSD/Stage3_3 Test.unity
  Assets/Student/HSD/UseItem.asset
  Assets/Student/HSD/UseItem.asset.meta
Labels: Merge, Feat

#105 [feat] 플롤로그씬 추가
  Assets/Student/JWJ/Prefabs/BossDoor.prefab
  Assets/Student/JWJ/Prefabs/BossDoor.prefab.meta
  Assets/Student/JWJ/Scenes/Stages/Prolog.unity
  Assets/Student/JWJ/Scenes/Stages/Prolog.unity.meta
  Assets/Student/JWJ/Scenes/Stages/Stage1_1.unity
  Assets/Student/JWJ/Scenes/Stages/Stage1_3.unity
  Assets/Student/JWJ/Scripts/BossRoomDoor.cs
  Assets/Student/JWJ/Scripts/OpeninDialogue.cs
  Assets/Student/JWJ/Scripts/StartDialogue.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: Merge, Feat

#108 [Feat] 합치기 누락물
  Assets/Animation/ExplosionMonster.meta
  Assets/Animation/Player.meta
  Assets/Animation/Props.meta
  Assets/Prefabs/BossPattern.meta
  Assets/Scripts/Boss.meta
  Assets/Scripts/UI/Accessories.meta
  Assets/Scripts/UI/Dialogue.meta
  Assets/Scripts/UI/Interactable.meta
  Assets/UIAnim/Dialogue.meta
Labels: Edit, Merge

#110 [Feat] Item 추가 기능
  Assets/Scripts/Data/DataDownloader.cs
  Assets/Scripts/Manager/Manager.cs
  Assets/Scripts/Manager/TableManager.cs
  Assets/Scripts/Manager/TableManager.cs.meta
  Assets/Scripts/Status/Monster/MonsterStat.cs
  Assets/Scripts/Status/PlayerStatus.cs
Labels: Merge, Feat

#109 [Feat] flute, cymbals particle
  Assets/Data/WeaponData/Trumpet.asset
  Assets/Prefabs/Projectile/First_TrumpetProjectile2.prefab
  Assets/Prefabs/Projectile/Fist_FluteProjectile.prefab
  Assets/Prefabs/Projectile/GunProjectile1.prefab
  Assets/Prefabs/Projectile/Second_FluteProjectile.prefab
  Assets/Prefabs/Projectile/Second_TrumpetProjectile2 1.prefab
  Assets/Prefabs/Projectile/ShaderCymbalsProjectile.prefab
  Assets/Prefabs/Projectile/Third_FluteProjectile.prefab
  Assets/Prefabs/Projectile/Third_TrumpetProjectile2 2.prefab
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Student/JHT/JHT_HSD_11.unity
  Assets/Student/JHT/Scene/TitleScene.unity
Labels: Merge, Feat

#111 Feat/UI title
  Assets/Data/WeaponData/Cymbals.asset
  Assets/Data/WeaponData/Flute.asset
  Assets/Data/WeaponData/Gun.asset
  Assets/Data/WeaponData/Trumpet.asset
  Assets/Data/WeaponData/Violin.asset
  Assets/Scripts/Data/DataDownloader.cs
  Assets/Scripts/Data/Weapon.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveObject.cs
  Assets/Scripts/Item/Accessories/EffectRandomAttacker.cs
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/Weapon/Cymbals.cs
  Assets/Scripts/Weapon/Flute.cs
  Assets/Scripts/Weapon/Gun.cs
  Assets/Scripts/Weapon/MusicWeapon.cs
  Assets/Scripts/Weapon/Trumpet.cs
  Assets/Scripts/Weapon/Violin.cs
  Assets/Student/JHT/JHT_HSD_11.unity
  Assets/Student/JHT/Scripts/JHT_PlayerWeapon.cs
Labels: Edit, Merge, Feat

#114 [fix] 샵 시스템 수정
  Assets/Scripts/UI/ShopUI/ShopOpen.cs
  Assets/Scripts/UI/ShopUI/ShopPresenter.cs
  Assets/Scripts/UI/ShopUI/ShopView.cs
  Assets/Student/JWJ/Scenes/Stages/Stage1_1.unity
Labels: Edit, Merge

#125 [Feat] Trumpet Projectile sprite setting
  Assets/Animation/Projectile.meta
  Assets/Animation/Projectile/Trumpet.controller
  Assets/Animation/Projectile/Trumpet.controller.meta
  Assets/Animation/Projectile/TrumpetAnim.anim
  Assets/Animation/Projectile/TrumpetAnim.anim.meta
  Assets/Data/WeaponData/Trumpet.asset
  Assets/Prefabs/Projectile/First_TrumpetProjectile2.prefab
  Assets/Prefabs/Projectile/Second_TrumpetProjectile2 1.prefab
  Assets/Prefabs/Projectile/Third_TrumpetProjectile2 2.prefab
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Scripts/Projectile/TrumpetProjectile.cs
  Assets/Student/JHT/JHT_HSD_11.unity
Labels: Merge, Feat

#132 [Feat] Cymbals Projectile sprite
  Assets/Data/WeaponData/Cymbals.asset
  Assets/Data/WeaponData/Flute.asset
  Assets/Data/WeaponData/Gun.asset
  Assets/Data/WeaponData/Violin.asset
  Assets/Prefabs/Projectile/ShaderCymbalsProjectile.prefab
  Assets/Student/HSD/Shader/ShockWave.mat
Labels: Merge

#134 빌드 세팅 변경
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage1/Stage1_3.unity.meta
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage2/Stage2_3.unity.meta
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scenes/Stage3/Stage3_3.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: Merge

#136 Feat/mini map
  Assets/Prefabs/Map/Box_Green.prefab
  Assets/Prefabs/Map/Box_Red.prefab
  Assets/Prefabs/Map/Portal_Stage1.prefab
  Assets/Prefabs/Player.prefab
  Assets/Student/JWJ/MiniMap.meta
  Assets/Student/JWJ/MiniMap/BoxOnMiniMap.mat
  Assets/Student/JWJ/MiniMap/BoxOnMiniMap.mat.meta
  Assets/Student/JWJ/MiniMap/MiniMap.mat
  Assets/Student/JWJ/MiniMap/MiniMap.mat.meta
  Assets/Student/JWJ/MiniMap/MiniMapTextrue.renderTexture
  Assets/Student/JWJ/MiniMap/MiniMapTextrue.renderTexture.meta
  Assets/Student/JWJ/MiniMap/PlayerOnMiniMap.mat
  Assets/Student/JWJ/MiniMap/PlayerOnMiniMap.mat.meta
  Assets/Student/JWJ/MiniMap/PortalOnMiniMap.mat
  Assets/Student/JWJ/MiniMap/PortalOnMiniMap.mat.meta
  Assets/Student/JWJ/Prefabs/Rooms 1-1.prefab
  Assets/Student/JWJ/Prefabs/Rooms 1-1.prefab.meta
  Assets/Student/JWJ/Scenes/Stages/Stage1_1.unity
  Assets/Student/JWJ/Scenes/Stages/Stage1_2.unity
  Assets/Student/JWJ/Scenes/Stages/Stage1_3.unity
  Assets/Student/JWJ/Sprites/MiniMapController.cs
  Assets/Student/JWJ/Sprites/MiniMapController.cs.meta
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
Labels: Feat

#137 [edit] 몬스터스포너 충돌문제 해결
  Assets/Prefabs/Player.prefab
  Assets/Student/JWJ/Scenes/Stages/Stage1_1.unity
  Assets/Student/JWJ/Scenes/Stages/Stage1_2.unity
  ProjectSettings/TagManager.asset
Labels: Edit, Merge

#146 Feat/merge
  Assets/Data/Acc/Effect/2015_DelayEffect.asset
  Assets/Data/Acc/Effect/2015_DelayEffect.asset.meta
  Assets/Prefabs/BossPattern/BossCirclePattern.prefab
  Assets/Prefabs/BossPattern/BossLinePattern.prefab
  Assets/Prefabs/BossPattern/Piano/PianoBlack.prefab
  Assets/Prefabs/BossPattern/Piano/PianoWhiteLeft.prefab
  Assets/Prefabs/BossPattern/Piano/PianoWhiteMiddle.prefab
  Assets/Prefabs/BossPattern/Piano/PianoWhiteRigth.prefab
  Assets/Prefabs/FX/EffectObj/Fireball.prefab
  Assets/Prefabs/FX/EffectObj/Fireball.prefab.meta
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scripts/Boss/BossPatternObject.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveObject.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveProjectile.cs
  Assets/Student/HSD/Accessories.asset
  Assets/Student/HSD/Accessories.asset.meta
  Assets/Student/HSD/Stage3_3 Test.unity
  Assets/Student/HSD/UseItem.asset
Labels: Edit, Merge

#148 [fix] 여러가지 수정
  Assets/Scenes/Prolog.unity
  Assets/Scenes/Stage1/Stage1_2.unity
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/TitleScene.unity
  Assets/Scripts/UI/Dialogue/StartDialogue.cs
Labels: Edit

#150 Feat/merge
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scripts/FloatStat.cs
  Assets/Scripts/GoldStat.cs
  Assets/Scripts/IntStat.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveEffectController.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveProjectile.cs
  Assets/Scripts/Manager/AudioManager.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Manager/PoolManager.cs
  Assets/Scripts/Manager/UI_Manager.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/UI/Accessories/AccessoriesPanel.cs
  Assets/Scripts/UI/Ending/PlayerDie.cs
  Assets/Scripts/UI/FadeScreen.cs
  Assets/Scripts/UI/Gold/GoldPanel.cs
  Assets/Scripts/UI/Weapon/WeaponSlot.cs
  Assets/Scripts/Utile/Utile.cs
Labels: Merge, Feat

#153 [Fix] 플레이어 위치를 찾지 못하는 버그 수정
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scripts/Item/Accessories/AccessoriesEffect/OrbitEffect.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveEffectController.cs
  Assets/Scripts/Item/Accessories/OrbitController.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Scripts/Status/PlayerStatus.cs
Labels: Edit, Merge

#154 [Fix] Attack animator
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerWeaponController.cs
Labels: Edit, Merge, Feat

#156 [Edit] UI 이미지 업데이트
  Assets/Prefabs/UI/DialogueUI.prefab
  Assets/Prefabs/UI/Heart.prefab
  Assets/Scenes/Prolog.unity
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scripts/UI/Accessories/AccessoriesSlot.cs
  Assets/Scripts/UI/Weapon/WeaponSlot.cs
Labels: Edit, Merge

#157 [edit] UI Fix
  Assets/Prefabs/UI/InteractableUI.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
Labels: Edit, Merge

#164 [Fix] 보스가 플레이어를 못찾는 문제 해결
  Assets/Prefabs/BossCanvas.prefab
  Assets/Prefabs/BossPattern/BossCirclePattern.prefab
  Assets/Prefabs/BossPattern/Laser.prefab
  Assets/Prefabs/BossPattern/Line.prefab
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scripts/Boss/Boss1/BossMonsterFSM.cs
  Assets/Scripts/Boss/Boss2/EllieLine.cs
  Assets/Scripts/Boss/BossPatternObject.cs
  Assets/Scripts/Manager/PoolManager.cs
  Assets/Student/HSD/Stage1_3.unity
  Assets/Student/HSD/Stage2_3.unity
Labels: Edit, Merge

#167 [eidt] 최대체력 하트 반영문제 해결
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Scripts/UI/Dialogue/StartDialogue.cs
Labels: Edit, Merge

#168 [Fix] Projectile Scale Fix
  Assets/Prefabs/Coin.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_BlueIce.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_Dark.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_Fire05.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_GreenCircle.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_GreenIce.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_GreenImpact.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_OrangeImpact.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_PurpleEffect.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_PurpleImpact.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_RedEffect.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_RedIce.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_elec.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_ice.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_purpleImpactWind 1.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_purpleImpactWind.prefab
Labels: Merge, Feat

#169 [Issue] Sound
  Assets/Prefabs/Projectile/First_TrumpetProjectile2.prefab
  Assets/Prefabs/Projectile/Fist_FluteProjectile.prefab
  Assets/Prefabs/Projectile/GunProjectile1.prefab
  Assets/Prefabs/Projectile/Second_TrumpetProjectile2 1.prefab
  Assets/Prefabs/Projectile/ShaderCymbalsProjectile.prefab
  Assets/Prefabs/Projectile/Third_TrumpetProjectile2 2.prefab
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Scripts/Weapon/Trumpet.cs
Labels: Bug, Merge

#172 [Fix] default weapon
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/UI/Popup/StatusPopUp.cs
  Assets/Scripts/UI/Weapon/WeaponSlotPresenter.cs
  Assets/Student/JHT/JHTStageStage1_1.unity
  Assets/Student/JHT/JHTStageStage1_1.unity.meta
Labels: Edit, Merge

#175 [Fix[ MonsterSound
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter1/chat1_DepravedSlime/chat1_DepravedSlime.controller
  Assets/Prefabs/Coin.prefab
  Assets/Scripts/Monster/Proxy/AnimationEventProxy.cs
  Assets/Student/YTW/TestScene.unity
Labels: Merge, Feat

#176 [fea] 오디오 추가
  Assets/Scripts/Interactable/Portal/Portal.cs
  Assets/Scripts/UI/Accessories/AccessoriesChangePanel.cs
  Assets/Scripts/UI/Accessories/ToolTip.cs
  Assets/Scripts/UI/ShopUI/ShopView.cs
  Assets/Scripts/UI/Title/TitleCanvas.cs
  Assets/Student/JWJ/Scripts/DialogueAfterCh1.cs
  Assets/Student/JWJ/Scripts/DialogueAfterCh2.cs
Labels: Merge, Feat

#178 [edit] 씬 수정
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage1/Stage1_2.unity
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage2/Stage2_1.unity
  Assets/Scenes/Stage2/Stage2_2.unity
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage3/Stage3_1.unity
  Assets/Scenes/Stage3/Stage3_2.unity
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scripts/Manager/PoolManager.cs
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Scripts/UI/Accessories/ToolTip.cs
Labels: Edit, Merge

#179 [Feat] Add PlayerStatus
  Assets/Data/WeaponData/Violin.asset
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Scripts/UI/Popup/StatusPopUp.cs
  Assets/Student/HSD/Scripts/Demo.cs
Labels: Merge, Feat

#177 Test/stage test
  Assets/Prefabs/MonsterPrefabs/Chapter2_Monster/Ellie.prefab
  Assets/Prefabs/MonsterPrefabs/Chapter3_Monster/Tobeben.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scenes/Stage1/Stage1_1_Profiles.meta
  Assets/Scenes/Stage1/Stage1_1_Profiles/Post-process Volume Profile.asset
  Assets/Scenes/Stage1/Stage1_1_Profiles/Post-process Volume Profile.asset.meta
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage2/Stage2_1.unity
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage3/Stage3_1.unity
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scenes/TitleScene.unity
  Assets/Scripts/Boss/Boss1/BossFSM_1.cs
  Assets/Scripts/Boss/Boss2/BossFSM_2.cs
  Assets/Scripts/Boss/Boss2/BossTargetLock.cs
  Assets/Scripts/Boss/Boss3/BossFSM_3.cs
  Assets/Scripts/Boss/Boss3/BossLinePattern.cs
  Assets/Scripts/Boss/Boss3/CrossState_3.cs
  Assets/Scripts/Boss/Boss3/GlissandoPattern.cs
  Assets/Scripts/Boss/Boss3/PianoPattern.cs
  Assets/Scripts/Boss/BossCircleSpawnPattern.cs
  Assets/Scripts/Data/DataDownloader.cs
  Assets/Scripts/Manager/AudioManager.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/MonsterSpawner/MonsterSpawnerManager.cs
  Assets/Student/HSD/Scripts/Boss/BossPattern_Sound.cs
  Assets/Student/HSD/Scripts/Boss/BossPattern_Sound.cs.meta
  Assets/Student/HSD/Scripts/StageSetting.cs
  Assets/Student/HSD/Scripts/StageSetting.cs.meta
  Assets/Student/HSD/Stage2_3.unity
Labels: Edit, Merge, Feat

#181 [edit] 벽뚫는 문제 해결
  Assets/Prefabs/Coin.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
  ProjectSettings/TimeManager.asset
Labels: Edit, Merge

#185 [Fix] Mosnter sound
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter1/chat1_DepravedSlime/chat1_DepravedSlime_Attack.anim
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter1/chat1_Zombie/chat1_Zombie_Attack.anim
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter2/chat2_DestructDog/chat2_DestructDog_Attack.anim
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter2/chat2_GiantSlime/chat2_GiantSlime_Attack.anim
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter3/chat3_MusicBox/chat3_MusicBox_Attack.anim
  Assets/Animation/ExplosionMonster/ExplosionMonsterAnim/Chapter3/chat3_Note/chat3_Note_Attack.anim
  Assets/Animation/MeleeMonster/Chapter1/chat1_Citizen/chat1_Citizen_Die.anim
  Assets/Animation/MeleeMonster/Chapter1/chat1_Fanatic/chat1_Fanatic_Die.anim
  Assets/Animation/MeleeMonster/Chapter2/chat2_Fanatic/chat2_Fanatic_Die.anim
  Assets/Animation/MeleeMonster/Chapter2/chat2_MadDog/chat2_MadDog_Die.anim
  Assets/Animation/MeleeMonster/Chpater3/chat3_Butcher/chat3_Butcher_Die.anim
  Assets/Animation/MeleeMonster/Chpater3/chat3_Musician/chat3_Musician_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_Baton/chat1_Baton_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_Note/chat1_Note_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_NoteFragments/chat1_NoteFragments_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_NoteLump/chat1_NoteLump_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_ScorePiece/chat1_ScorePiece_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_Slime/chat1_Slime_Die.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_TrashCan/chat1_TrashCan_Die.anim
  Assets/Animation/RangedMonster/Chapter2/Chat2_Score/chat2_Score_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_BlackWolf/chat2_BlackWolf_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_Metronome/chat2_Metronome_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_Orb/chat2_Orb_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_Saltato/chat2_Saltato_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_Slime/chat2_Slime_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_StageDecoration/chat2_StageDecoration_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Beast/chat3_Beast_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Crystal/chat3_Crystal_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_GiantNote/chat3_GiantNote_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Harp/chat3_Harp_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Slime/chat3_Slime_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Spider/chat3_Spider_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Tuba/chat3_Tuba_Die.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Wolf/chat3_Wolf_Die.anim
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_RedEffect.prefab
  Assets/Scripts/Monster/Projectile_Controller.cs
  Assets/Scripts/Monster/Proxy/AnimationEventProxy.cs
  Assets/Student/YTW/TestScene.unity
Labels: Bug, Merge, Feat

#188 Test/stage test
  Assets/Prefabs/BossPattern/Line.prefab
  Assets/Prefabs/Gun.prefab
  Assets/Prefabs/MonsterPrefabs/Chapter3_Monster/Tobeben.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scenes/TitleScene.unity
  Assets/Scripts/Boss/Boss1/BossBaseState.cs
  Assets/Scripts/Boss/Boss2/BossFSM_2.cs
  Assets/Scripts/Boss/Boss2/BossPatternController_2.cs
  Assets/Scripts/Boss/Boss3/BossFSM_3.cs
  Assets/Scripts/Boss/Boss3/BossLinePattern.cs
  Assets/Scripts/Boss/Boss3/BossPatternController_3.cs
  Assets/Scripts/Data/Weapon.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Manager/InputManager.cs
  Assets/Scripts/Manager/UI_Manager.cs
  Assets/Scripts/Monster/FSM/SheetMusicMonsterFSM.cs
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/UI/Accessories/AccessoriesChangePanel.cs
  Assets/Scripts/UI/AnimationUI_Base.cs
  Assets/Scripts/UI/Dialogue/StartDialogue.cs
  Assets/Scripts/UI/ShopUI/ShopOpen.cs
  Assets/Scripts/UI/Title/TitleCanvas.cs
Labels: Edit, Merge

#190 [Feat] Add Weapon SFX
  Assets/Prefabs/Projectile/First_TrumpetProjectile2.prefab
  Assets/Prefabs/Projectile/Fist_FluteProjectile.prefab
  Assets/Prefabs/Projectile/GunProjectile1.prefab
  Assets/Prefabs/Projectile/Ray.prefab
  Assets/Prefabs/Projectile/Second_FluteProjectile.prefab
  Assets/Prefabs/Projectile/Second_TrumpetProjectile2 1.prefab
  Assets/Prefabs/Projectile/ShaderCymbalsProjectile.prefab
  Assets/Prefabs/Projectile/Third_FluteProjectile.prefab
  Assets/Prefabs/Projectile/Third_TrumpetProjectile2 2.prefab
  Assets/Scenes/TitleScene.unity
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Scripts/Projectile/TrumpetProjectile.cs
  Assets/Scripts/Projectile/ViolinProjectile.cs
  Assets/Scripts/Weapon/MusicWeapon.cs
Labels: Merge, Feat

#191 [Fix] stat
  Assets/Animation/Projectiles/Circle/DarkCricle/DarkEffect.anim
  Assets/Animation/RangedMonster/Chapter1/chat1_Baton/chat1_Baton_Die.anim
  Assets/Animation/RangedMonster/Chapter2/chat2_BlackWolf/chat2_BlackWolf_Attack.anim
  Assets/Animation/RangedMonster/Chapter3/chat3_Harp/chat3_Harp_Attack.anim
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_Dark_Homing.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/Projectile/Projectile_Dark_Homing.prefab.meta
  Assets/Student/YTW/TestScene.unity
Labels: Merge, Feat

#192 [Feat] 무적, 회피 시 다르게 출력
  Assets/Prefabs/MonsterPrefabs/Chapter3_Monster/Tobeben.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scripts/Boss/Boss3/BossPatternController_3.cs
  Assets/Scripts/EntityFX.cs
  Assets/Scripts/Item/Accessories/EffectObject/PassiveEffectController.cs
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Scripts/UI/DamagePopupText.cs
  Assets/Student/HSD/Scripts/PostProcessing_Controller.cs
  Assets/Student/HSD/Scripts/PostProcessing_Controller.cs.meta
Labels: Edit, Merge

#194 [edit] 피드백 수정
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scenes/Stage1/Stage1_2.unity
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage2/Stage2_1.unity
  Assets/Scenes/Stage2/Stage2_2.unity
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage3/Stage3_1.unity
  Assets/Scenes/Stage3/Stage3_2.unity
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scripts/Manager/AudioManager.cs
  Assets/Scripts/Monster/Monster.cs
  Assets/Scripts/Monster/Proxy/AnimationEventProxy.cs
  Assets/Scripts/MonsterSpawner/MonsterSpawnTrigger.cs
  Assets/Scripts/MonsterSpawner/MonsterSpawnerManager.cs
  Assets/Scripts/Player/PlayerWeaponController.cs
  Assets/Student/HSD/Scripts/PostProcessing_Controller.cs
  Assets/Student/JWJ/Scripts/DialogueAfterCh2.cs
  ProjectSettings/TimeManager.asset
Labels: Edit, Merge

#195 Test/stage test
  Assets/Prefabs/Gun.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scenes/Stage1/Stage1_3.unity
  Assets/Scenes/Stage2/Stage2_3.unity
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Student/HSD/Scripts/PostProcessing_Controller.cs
Labels: Edit, Merge

#197 [Feat] 게임 진행 및 타이틀 상태 구분
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Projectile/ShaderCymbalsProjectile.prefab
  Assets/Scenes/TitleScene.unity
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Manager/UI_Manager.cs
  Assets/Scripts/UI/Dialogue/StartDialogue.cs
  Assets/Scripts/UI/Ending/PlayerDie.cs
  Assets/Scripts/UI/Title/TitleCanvas.cs
  Assets/Student/HSD/Shader/ShockWave.mat
Labels: Edit, Merge, Feat

#199 [Fix] StatusPopUp not show
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/UI/Popup/StatusPopUp.cs
Labels: Edit, Merge

#201 [Fix] statusPopUp fix
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/UI/Popup/StatusPopUp.cs
Labels: Edit, Merge

#203 [feat] 엔딩 유아이 추가
  Assets/Scenes/Stage3/Stage3_3.unity
  Assets/Student/JWJ/Scripts/DialogueBoss.cs
  Assets/Student/JWJ/Scripts/DoorClose.cs
  Assets/Student/JWJ/Scripts/DoorClose.cs.meta
Labels: Merge, Feat

#204 [Feat] trumpet sound rand
  Assets/Scripts/Projectile/TrumpetProjectile.cs
Labels: Edit, Merge

#209 Fix/수정 요청사항 수정
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Stage1/Stage1_1.unity
  Assets/Scenes/Stage1/Stage1_2.unity
  Assets/Scripts/Monster/FSM/ExplosionMonsterFSM.cs
  Assets/Scripts/UI/Ending/PlayerDie.cs
  Assets/Scripts/UI/Popup/PopUpCanvas.cs
  Assets/Scripts/UI/ShopUI/ShopOpen.cs
  Assets/Scripts/UI/ShopUI/ShopView.cs
  ProjectSettings/Physics2DSettings.asset
Labels: Edit, Merge

#216 [Fix] Pause issue
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/UI/Title/TitleCanvas.cs
Labels: Edit, Merge
