Repository HSD06040/2D_Roguelike, pull requests merged in 2025-06, with the labels that each got.

#2 develop merge
  Assets/2D_Roguelike_Resource.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/SceneTemplateSettings.json
  README.md
Labels: Merge

#3 [Feat] test weapon
  Assets/Student/JHT/Sciptable.meta
  Assets/Student/JHT/Sciptable/MusicWeapon.meta
  Assets/Student/JHT/Sciptable/MusicWeapon/Basic.asset
  Assets/Student/JHT/Sciptable/MusicWeapon/Basic.asset.meta
  Assets/Student/JHT/Scripts/Item.cs
  Assets/Student/JHT/Scripts/Item.cs.meta
  Assets/Student/JHT/Scripts/MusicWeapon.cs
  Assets/Student/JHT/Scripts/MusicWeapon.cs.meta
  Assets/Student/JHT/Scripts/Weapon.cs
  Assets/Student/JHT/Scripts/Weapon.cs.meta
  Assets/Student/JHT/TestScene.unity
Labels: Merge, Feat

#4 Feat/managers
  Assets/Scripts/Manager.meta
  Assets/Scripts/Manager/AudioManager.cs
  Assets/Scripts/Manager/AudioManager.cs.meta
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/DataManager.cs.meta
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Manager/GameManager.cs.meta
  Assets/Scripts/Manager/Manager.cs
  Assets/Scripts/Manager/Manager.cs.meta
  Assets/Scripts/Manager/PoolManager.cs
  Assets/Scripts/Manager/PoolManager.cs.meta
  Assets/Scripts/Manager/ResourcesManager.cs
  Assets/Scripts/Manager/ResourcesManager.cs.meta
  Assets/Scripts/Manager/Singleton.cs
  Assets/Scripts/Manager/Singleton.cs.meta
  Assets/Scripts/Manager/UI_Manager.cs
  Assets/Scripts/Manager/UI_Manager.cs.meta
Labels: Merge, Feat

#5 [feat] player 추가, 이동 구현, 발사 구현
  Assets/Student/JWJ/JWJ.unity
  Assets/Student/JWJ/JWJ.unity.meta
  Assets/Student/JWJ/Prefabs.meta
  Assets/Student/JWJ/Prefabs/Bullet.prefab
  Assets/Student/JWJ/Prefabs/Bullet.prefab.meta
  Assets/Student/JWJ/Prefabs/Player.prefab
  Assets/Student/JWJ/Prefabs/Player.prefab.meta
  Assets/Student/JWJ/Scripts/Bullet.cs
  Assets/Student/JWJ/Scripts/Bullet.cs.meta
  Assets/Student/JWJ/Scripts/DamageSystemExample.cs
  Assets/Student/JWJ/Scripts/DamageSystemExample.cs.meta
  Assets/Student/JWJ/Scripts/PlayerController.cs
  Assets/Student/JWJ/Scripts/PlayerController.cs.meta
  Assets/Student/JWJ/Scripts/PlayerControlletExample.cs
  Assets/Student/JWJ/Scripts/PlayerControlletExample.cs.meta
Labels: Feat

#7 [Feat] 데이터 다운로더 제작 및 테스트완료
  Assets/Scripts/Data.meta
  Assets/Scripts/Data/DataDownloader.cs
  Assets/Scripts/Data/DataDownloader.cs.meta
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/Manager.cs
Labels: Feat

#9 {Feat] 대미지 시스템, 악기 변경 시스템
  Assets/Student/JWJ/JWJ.unity
  Assets/Student/JWJ/Prefabs/Bullet.prefab
  Assets/Student/JWJ/Prefabs/Player.prefab
  Assets/Student/JWJ/Prefabs/TestWeapon.prefab
  Assets/Student/JWJ/Prefabs/TestWeapon.prefab.meta
  Assets/Student/JWJ/Scripts/Bullet.cs
  Assets/Student/JWJ/Scripts/MonsterTest.cs
  Assets/Student/JWJ/Scripts/MonsterTest.cs.meta
  Assets/Student/JWJ/Scripts/OldScripts.meta
  Assets/Student/JWJ/Scripts/OldScripts/Bullet.cs
  Assets/Student/JWJ/Scripts/OldScripts/Bullet.cs.meta
  Assets/Student/JWJ/Scripts/OldScripts/DamageSystemExample.cs
  Assets/Student/JWJ/Scripts/OldScripts/DamageSystemExample.cs.meta
  Assets/Student/JWJ/Scripts/OldScripts/PlayerControlletExample.cs
  Assets/Student/JWJ/Scripts/OldScripts/PlayerControlletExample.cs.meta
  Assets/Student/JWJ/Scripts/PlayerController.cs
  Assets/Student/JWJ/Scripts/PlayerStatusController.cs
  Assets/Student/JWJ/Scripts/PlayerStatusController.cs.meta
  Assets/Student/JWJ/Scripts/StatusController.cs
  Assets/Student/JWJ/Scripts/StatusController.cs.meta
  Assets/Student/JWJ/Scripts/WeaponTest.cs
  Assets/Student/JWJ/Scripts/WeaponTest.cs.meta
  ProjectSettings/TagManager.asset
Labels: Feat

#11 Feat/music weapon
  Assets/Scripts/Data/DataDownloader.cs
  Assets/Student/JHT/JHT_TestScene.unity
  Assets/Student/JHT/Prefabs/BasicWeapon.prefab
  Assets/Student/JHT/Prefabs/WeaponSample 1.prefab
  Assets/Student/JHT/Prefabs/WeaponSample 2.prefab
  Assets/Student/JHT/Prefabs/WeaponSample.prefab
  Assets/Student/JHT/Prefabs/test2.prefab
  Assets/Student/JHT/Prefabs/test3.prefab
  Assets/Student/JHT/Sciptable/MusicWeapon/Basic.asset
  Assets/Student/JHT/Sciptable/MusicWeapon/test2.asset
  Assets/Student/JHT/Sciptable/MusicWeapon/test3.asset
  Assets/Student/JHT/Scripts/JHT_Test_Player.cs
  Assets/Student/JHT/Scripts/MusicWeapon.cs
  Assets/Student/JHT/Scripts/PlayerFight.cs
  Assets/Student/JHT/Scripts/Weapon.cs
Labels: Merge, Feat

#12 [Feat] Weapon bullet from weaponPosition to checkPoint [Issue] Projec…
  Assets/Student/JHT/Particles/Particle System1.prefab
  Assets/Student/JHT/Particles/Particle System2.prefab
  Assets/Student/JHT/Particles/Particle System3.prefab
  Assets/Student/JHT/Prefabs/Projectile1.prefab
  Assets/Student/JHT/Prefabs/Projectile1.prefab.meta
  Assets/Student/JHT/Prefabs/Projectile2.prefab
  Assets/Student/JHT/Prefabs/Projectile2.prefab.meta
  Assets/Student/JHT/Prefabs/Projectile3.prefab
  Assets/Student/JHT/Prefabs/Projectile3.prefab.meta
  Assets/Student/JHT/Prefabs/bulle2.prefab
  Assets/Student/JHT/Prefabs/bulle2.prefab.meta
  Assets/Student/JHT/Prefabs/bulle3.prefab
  Assets/Student/JHT/Prefabs/bulle3.prefab.meta
  Assets/Student/JHT/Prefabs/bullet.prefab
  Assets/Student/JHT/Prefabs/bullet.prefab.meta
  Assets/Student/JHT/Prefabs/test1.prefab
  Assets/Student/JHT/Prefabs/test1.prefab.meta
  Assets/Student/JHT/Prefabs/test2.prefab
  Assets/Student/JHT/Prefabs/test3.prefab
  Assets/Student/JHT/Sciptable/MusicWeapon/Basic.asset
  Assets/Student/JHT/Sciptable/MusicWeapon/test2.asset
  Assets/Student/JHT/Sciptable/MusicWeapon/test3.asset
  Assets/Student/JHT/Scripts/JHT_Test_Player.cs
  Assets/Student/JHT/Scripts/PlayerFight.cs
  Assets/Student/JHT/Scripts/Projectile/Projectile.cs
  Assets/Student/JHT/Scripts/Weapon.cs
Labels: Bug, Merge, Feat

#14 [Feat] Add AreaProjectile
  Assets/Student/JHT/Scripts/JHT_Test_Player.cs
  Assets/Student/JHT/Scripts/PlayerFight.cs
  Assets/Student/JHT/Scripts/Projectile/AreaProjectile.cs
  Assets/Student/JHT/Scripts/Projectile/AreaProjectile.cs.meta
  Assets/Student/JHT/Scripts/Projectile/Projectile.cs
  Assets/Student/JHT/Scripts/Weapon.cs
Labels: Edit, Merge

#16 [Feat] Shockwave Shader
  Assets/Scripts/Manager/UI_Manager.cs
  Assets/Settings/Renderer2D.asset
  Assets/Settings/UniversalRP.asset
  Assets/Student/HSD/159Z_2107.w026.n002.628B.p1.628.jpg
  Assets/Student/HSD/159Z_2107.w026.n002.628B.p1.628.jpg.meta
  Assets/Student/HSD/Scripts/UI.meta
  Assets/Student/HSD/Shader.meta
  Assets/Student/HSD/Shader/ShockWave.mat
  Assets/Student/HSD/Shader/ShockWave.mat.meta
  Assets/Student/HSD/Shader/ShockWave.shadergraph
  Assets/Student/HSD/Shader/ShockWave.shadergraph.meta
  Assets/Student/HSD/Shader/ShockWaveScreen.shadergraph
  Assets/Student/HSD/Shader/ShockWaveScreen.shadergraph.meta
  Assets/Student/HSD/TestScene.unity
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/TagManager.asset
Labels: Merge, Feat

#19 [Feat] 플레이어 대미지 쿨타임 추가
  Assets/Student/JWJ/JWJ.unity
  Assets/Student/JWJ/Scripts/PlayerController.cs
  Assets/Student/JWJ/Scripts/PlayerStatusController.cs
Labels: Feat

#22 [Fix] Weapon Coroutine [Refactor] Particle Code Change
  Assets/Student/JHT/Scripts/JHT_Test_Player.cs
  Assets/Student/JHT/Scripts/MusicWeapon.cs
  Assets/Student/JHT/Scripts/PlayerFight.cs
Labels: Edit, Merge

#27 [Edit] 무기소지 리밋 추가
  Assets/Student/JWJ/Scripts/PlayerController.cs
Labels: Edit

#28 [Edit] 무기획득, 선택 방식 변경
  Assets/Student/JWJ/Scripts/PlayerController.cs
Labels: Edit

#29 [Fix] NavMeshPlus로 인한 문제 수정
  Assets/Config/NavMeshPlus-master/Gizmos.meta
  Assets/Config/NavMeshPlus-master/Gizmos/NavMeshLink Icon.png.meta
  Assets/Config/NavMeshPlus-master/Gizmos/NavMeshModifierVolume Icon.png.meta
  Assets/Config/NavMeshPlus-master/Gizmos/NavMeshSurface Icon.png.meta
  Assets/Config/NavMeshPlus-master/Gizmos/NavMeshSurface2d Icon.png.meta
  Assets/Config/NavMeshPlus-master/Gizmos/NavMeshSurfaceGears Icon.png.meta
  Assets/Config/NavMeshPlus-master/LICENSE.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/AgentOverride2dEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/CollectSources2dEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/CollectSourcesCache2dEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshAgentAttributePropertyDrawer.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshAreaAttributePropertyDrawer.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshAssetManager.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshComponentsEditor.asmdef.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshComponentsGUIUtility.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshLinkEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshModifierEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshModifierTilemapEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Editor/RootSources2dEditor.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/AgentOverride2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/AgentRotate2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/AgentRotateSmooth2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/CollectSources2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/CollectSourcesCache2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/CollectTilemapSourcesCache2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshAgentAttribute.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshAreaAttribute.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshBuilder2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshBuilderState.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshComponents.asmdef.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtension.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshExtensionsProvider.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshLink.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshModifier.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshModifierTilemap.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshModifierVolume.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/NavMeshSurface.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/RootSources2d.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/RotateAgentInstantly.cs.meta
  Assets/Config/NavMeshPlus-master/NavMeshComponents/Scripts/RotateAgentSmoothly.cs.meta
  Assets/Config/NavMeshPlus-master/README.md.meta
  Assets/Config/NavMeshPlus-master/Unity.meta
  Assets/Config/NavMeshPlus-master/Unity/LICENSE.meta
  Assets/Config/NavMeshPlus-master/Unity/README.md.meta
  Assets/Config/NavMeshPlus-master/navmeshplus.pdf.meta
  Assets/Config/NavMeshPlus-master/package.json.meta
  Assets/Scripts/Manager/PoolManager.cs
  Assets/Student/HSD/Shader/ShockWave.mat
  Assets/Student/HSD/TestScene.unity
  Packages/manifest.json
  Packages/packages-lock.json
Labels: Bug, Edit

#32 [Feat] 맵 제작
  Assets/Scenes/Stage1_1.unity
  Assets/Scenes/Stage1_1.unity.meta
  Assets/Scenes/Stage1_2.unity
  Assets/Scenes/Stage1_2.unity.meta
  Assets/Scenes/Stage1_3.unity
  Assets/Scenes/Stage1_3.unity.meta
Labels: Merge

#34 [Feat] 플레이어와 악기 합치기
  Assets/Settings/Renderer2D.asset
  Assets/Student/HSD/Prototype.unity
  Assets/Student/HSD/Prototype.unity.meta
  Assets/Student/HSD/Scripts/Demo.cs
  Assets/Student/HSD/Scripts/Demo.cs.meta
  Assets/Student/HSD/Scripts/Player.meta
  Assets/Student/HSD/Scripts/Player/PlayerInput.cs
  Assets/Student/HSD/Scripts/Player/PlayerInput.cs.meta
  Assets/Student/HSD/Scripts/Player/PlayerWeaponController.cs
  Assets/Student/HSD/Scripts/Player/PlayerWeaponController.cs.meta
  Assets/Student/HSD/Shader/ShockWave.mat
  Assets/Student/HSD/TestScene.unity
  Assets/Student/JHT/Prefabs/Cymbals/Cymbals.prefab
  Assets/Student/JHT/Prefabs/Cymbals/CymbalsProjectile.prefab
  Assets/Student/JHT/Prefabs/Cymbals/ShaderCymbalsProjectile.prefab
  Assets/Student/JHT/Prefabs/Gun/GunProjectile1.prefab
  Assets/Student/JHT/Prefabs/Trumpet/Trumpet.prefab
  Assets/Student/JHT/Prefabs/Trumpet/TrumpetProjectile2.prefab
  Assets/Student/JHT/Sciptable/MusicWeapon/Cymbals.asset
  Assets/Student/JHT/Scripts/JHT_Test_Player.cs
  Assets/Student/JHT/Scripts/MusicWeapon.cs
  Assets/Student/JHT/Scripts/PlayerFight.cs
  Assets/Student/JHT/Scripts/Projectile/CymbalsProjectile.cs
  Assets/Student/JHT/Scripts/Projectile/Projectile.cs
  Assets/Student/JHT/Scripts/Weapon/Cymbals.cs
  Assets/Student/JHT/Scripts/Weapon/Gun.cs
  Assets/Student/JWJ/Scripts/PlayerController.cs
  Assets/Student/JWJ/Scripts/WeaponTest.cs
  ProjectSettings/TagManager.asset
Labels: Edit, Merge

#35 [feat] 플레이어 체력 하트 UI 구현
  Assets/Student/JWJ/JWJ.unity
  Assets/Student/JWJ/Prefabs/Heart.prefab
  Assets/Student/JWJ/Prefabs/Heart.prefab.meta
  Assets/Student/JWJ/Scripts/HealthHeart.cs
  Assets/Student/JWJ/Scripts/HealthHeart.cs.meta
  Assets/Student/JWJ/Scripts/PlayerStatusController.cs
  Assets/Student/JWJ/Scripts/Tester.cs
  Assets/Student/JWJ/Scripts/Tester.cs.meta
  Assets/Student/JWJ/Sprites.meta
  Assets/Student/JWJ/Sprites/Hearts.png
  Assets/Student/JWJ/Sprites/Hearts.png.meta
Labels: Merge, Feat

#36 Feat/music weapon projectile/jht
  Assets/Settings/Renderer2D.asset
  Assets/Student/HSD/Prototype.unity
  Assets/Student/HSD/Prototype.unity.meta
  Assets/Student/HSD/Scripts/Demo.cs
  Assets/Student/HSD/Scripts/Demo.cs.meta
  Assets/Student/HSD/Scripts/Player.meta
  Assets/Student/HSD/Scripts/Player/PlayerInput.cs
  Assets/Student/HSD/Scripts/Player/PlayerInput.cs.meta
  Assets/Student/HSD/Scripts/Player/PlayerWeaponController.cs
  Assets/Student/HSD/Scripts/Player/PlayerWeaponController.cs.meta
  Assets/Student/HSD/Shader/ShockWave.mat
  Assets/Student/HSD/TestScene.unity
  Assets/Student/JHT/JHT_Prototype.unity
  Assets/Student/JHT/JHT_Prototype.unity.meta
  Assets/Student/JHT/JHT_TestScene.unity
  Assets/Student/JHT/Prefabs/Cymbals/Cymbals.prefab
  Assets/Student/JHT/Prefabs/Cymbals/CymbalsProjectile.prefab
  Assets/Student/JHT/Prefabs/Cymbals/ShaderCymbalsProjectile.prefab
  Assets/Student/JHT/Prefabs/Gun/GunProjectile1.prefab
  Assets/Student/JHT/Prefabs/Trumpet/Trumpet.prefab
  Assets/Student/JHT/Prefabs/Trumpet/TrumpetProjectile2.prefab
  Assets/Student/JHT/Sciptable/MusicWeapon/Cymbals.asset
  Assets/Student/JHT/Scripts/JHT_Test_Player.cs
  Assets/Student/JHT/Scripts/MusicWeapon.cs
  Assets/Student/JHT/Scripts/PlayerFight.cs
  Assets/Student/JHT/Scripts/Projectile/CymbalsProjectile.cs
  Assets/Student/JHT/Scripts/Projectile/Projectile.cs
  Assets/Student/JHT/Scripts/Weapon/Cymbals.cs
  Assets/Student/JHT/Scripts/Weapon/Gun.cs
  Assets/Student/JWJ/Scripts/PlayerController.cs
  Assets/Student/JWJ/Scripts/WeaponTest.cs
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
Labels: Merge

#46 [Feat] Click Laser for Violin Weapon [Issue] click position
  Assets/Data/WeaponData/Violin.asset
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Scripts/Projectile/TestLaserProjectile.cs
  Assets/Scripts/Projectile/TrumpetProjectile.cs
  Assets/Scripts/Weapon/Violin.cs
  Assets/Student/JHT/JHT_Prototype.unity
  Assets/Student/JHT/Prefabs/Ray.prefab
  Assets/Student/JHT/Prefabs/Ray.prefab.meta
  Assets/Student/JHT/Scripts/JHT_PlayerWeapon.cs
  Assets/Student/JHT/Scripts/JHT_PlayerWeapon.cs.meta
  Assets/Student/JHT/Scripts/JHT_TestDemo.cs
  Assets/Student/JHT/Scripts/JHT_TestDemo.cs.meta
  Assets/Student/JHT/Scripts/TestSingleton.cs
  Assets/Student/JHT/Scripts/TestSingleton.cs.meta
  Assets/Student/JHT/Scripts/ViolinProjectile.cs
  Assets/Student/JHT/Scripts/ViolinProjectile.cs.meta
Labels: Bug, Merge, Feat

#47 Feat/demo
  Assets/Data/WeaponData/Cymbals.asset
  Assets/Data/WeaponData/Gun.asset
  Assets/Data/WeaponData/Trumpet.asset
  Assets/Data/WeaponData/Violin.asset
  Assets/Prefabs/Weapon/Cymbals.prefab
  Assets/Prefabs/Weapon/Gun.prefab
  Assets/Prefabs/Weapon/Trumpet.prefab
  Assets/Prefabs/Weapon/Violin.prefab
  Assets/Scripts/Data/Weapon.cs
  Assets/Scripts/FloatStat.cs
  Assets/Scripts/InputBind.cs
  Assets/Scripts/InputBind.cs.meta
  Assets/Scripts/IntStat.cs
  Assets/Scripts/Item/Item.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Manager/InputManager.cs
  Assets/Scripts/Manager/InputManager.cs.meta
  Assets/Scripts/Manager/Manager.cs
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/UI/AnimationUI_Base.cs
  Assets/Scripts/UI/AnimationUI_Base.cs.meta
  Assets/Scripts/UI/Gold.meta
  Assets/Scripts/UI/Gold/GoldPanel.cs
  Assets/Scripts/UI/Gold/GoldPanel.cs.meta
  Assets/Scripts/UI/Gold/GoldPresenter.cs
  Assets/Scripts/UI/Gold/GoldPresenter.cs.meta
  Assets/Scripts/UI/Popup.meta
  Assets/Scripts/UI/Popup/PopupText.cs
  Assets/Scripts/UI/Popup/PopupText.cs.meta
  Assets/Scripts/UI/Weapon.meta
  Assets/Scripts/UI/Weapon/WeaponSlot.cs
  Assets/Scripts/UI/Weapon/WeaponSlot.cs.meta
  Assets/Scripts/UI/Weapon/WeaponSlotPresenter.cs
  Assets/Scripts/UI/Weapon/WeaponSlotPresenter.cs.meta
  Assets/Scripts/Weapon/MusicWeapon.cs
  Assets/Student/HSD/Prototype.unity
  Assets/Student/HSD/Scripts/Demo.cs
  Assets/Student/HSD/Scripts/Player/PlayerWeaponController.cs
  Assets/Student/JWJ/JWJ.unity
  Assets/Student/JWJ/Scripts/ShopUI/ShopOpenTest.cs
  Assets/Student/JWJ/Scripts/ShopUI/ShopPresenter.cs
  Assets/Student/JWJ/Scripts/ShopUI/ShopSlotUI.cs
  Assets/Student/JWJ/Scripts/ShopUI/ShopView.cs
  Assets/UIAnim.meta
  Assets/UIAnim/Popup.meta
  Assets/UIAnim/Popup/In.anim
  Assets/UIAnim/Popup/In.anim.meta
  Assets/UIAnim/Popup/Popup.controller
  Assets/UIAnim/Popup/Popup.controller.meta
  Assets/UIAnim/Shop.meta
  Assets/UIAnim/Shop/In.anim
  Assets/UIAnim/Shop/In.anim.meta
  Assets/UIAnim/Shop/Out.anim
  Assets/UIAnim/Shop/Out.anim.meta
  Assets/UIAnim/Shop/Shop.controller
  Assets/UIAnim/Shop/Shop.controller.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: Edit, Merge, Feat

#50 [Feat] ItemEffect
  Assets/Data/WeaponData/Trumpet.asset
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Scripts/Weapon/Trumpet.cs
  Assets/Student/HSD/Scripts/Accessories.cs
  Assets/Student/HSD/Scripts/Effect/ItemEffect.cs
  Assets/Student/HSD/Scripts/Effect/PassiveEffect.cs
Labels: Edit, Merge, Feat

#53 [Edit] 플레이어 HP UI 수정
  Assets/Scripts/FloatStat.cs
  Assets/Scripts/IntStat.cs
  Assets/Scripts/Manager/DataManager.cs
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Scripts/Property.cs
  Assets/Scripts/Status/PlayerStatus.cs
  Assets/Student/JWJ/JWJ.unity
  Assets/Student/JWJ/Scripts/HeartUI/HealthHeart.cs
  Assets/Student/JWJ/Scripts/HeartUI/Tester.cs
  Assets/Student/JWJ/Sprites/ChatGPT_Image_Jun_25_2025_10_08_09_AM.png.meta
Labels: Feat

#59 [Feat] Change TakeDamage Material, Projectile Size
  Assets/Scripts/EntityFX.cs
  Assets/Scripts/Projectile/TrumpetProjectile.cs
  Assets/Student/JHT/Prefabs/FluteProjectile.prefab
  Assets/Student/JHT/Scripts/ViolinProjectile.cs
Labels: Merge, Feat

#61 [Feat] 몬스터 스포너, 몬스터 카운트
  Assets/Student/HSD/Prototype.unity
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (1).prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (1).prefab.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (2).prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (2).prefab.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (3).prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (3).prefab.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (4).prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (4).prefab.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (5).prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (5).prefab.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (6).prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle (6).prefab.meta
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle.prefab
  Assets/Student/JWJ/Prefabs/SpawnerTestPrefabs/Circle.prefab.meta
  Assets/Student/JWJ/Scripts/MonsterSpawner.meta
  Assets/Student/JWJ/Scripts/MonsterSpawner/MonsterSpawnTrigger.cs
  Assets/Student/JWJ/Scripts/MonsterSpawner/MonsterSpawnTrigger.cs.meta
  Assets/Student/JWJ/Scripts/MonsterSpawner/MonsterSpawnerManager.cs
  Assets/Student/JWJ/Scripts/MonsterSpawner/MonsterSpawnerManager.cs.meta
Labels: Merge, Feat

#62 Feat/maps
  Assets/New Terrain.asset
  Assets/New Terrain.asset.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/Stage1_1.unity
  Assets/Scenes/Stage2_1.unity
  Assets/Scenes/Stage2_1.unity.meta
  Assets/Scenes/Stage2_2.unity
  Assets/Scenes/Stage2_2.unity.meta
  Assets/Scenes/Stage2_3.unity
  Assets/Scenes/Stage2_3.unity.meta
  Assets/Scripts/box.meta
Labels: Merge

#66 Feat/monster material/jht
  Assets/Scripts/EntityFX.cs
Labels: Edit, Merge

#70 [feat] 상자, 포탈 상호작용 구현
  Assets/Scripts/Player/PlayerController.cs
  Assets/Scripts/Player/PlayerStatusController.cs
  Assets/Student/JWJ/Prefabs/Box.prefab
  Assets/Student/JWJ/Prefabs/Box.prefab.meta
  Assets/Student/JWJ/Prefabs/InteractableUI.prefab
  Assets/Student/JWJ/Prefabs/InteractableUI.prefab.meta
  Assets/Student/JWJ/Prefabs/Portal.prefab
  Assets/Student/JWJ/Prefabs/Portal.prefab.meta
  Assets/Student/JWJ/Scenes/Stage1_1.unity
  Assets/Student/JWJ/Scenes/Stage1_1.unity.meta
  Assets/Student/JWJ/Scenes/Stage1_2.unity
  Assets/Student/JWJ/Scenes/Stage1_2.unity.meta
  Assets/Student/JWJ/Scenes/Stage1_3.unity
  Assets/Student/JWJ/Scenes/Stage1_3.unity.meta
  Assets/Student/JWJ/Scenes/Stage2_1.unity
  Assets/Student/JWJ/Scenes/Stage2_1.unity.meta
  Assets/Student/JWJ/Scenes/Stage2_2.unity
  Assets/Student/JWJ/Scenes/Stage2_2.unity.meta
  Assets/Student/JWJ/Scenes/Stage2_3.unity
  Assets/Student/JWJ/Scenes/Stage2_3.unity.meta
  Assets/Student/JWJ/Scenes/Stage3_1.unity
  Assets/Student/JWJ/Scenes/Stage3_1.unity.meta
  Assets/Student/JWJ/Scenes/Stage3_2.unity
  Assets/Student/JWJ/Scenes/Stage3_2.unity.meta
  Assets/Student/JWJ/Scenes/Stage3_3.unity
  Assets/Student/JWJ/Scenes/Stage3_3.unity.meta
  Assets/Student/JWJ/Scenes/TestScene_JWJ.unity
  Assets/Student/JWJ/Scripts/Iinteractable.cs
  Assets/Student/JWJ/Scripts/Iinteractable.cs.meta
  Assets/Student/JWJ/Scripts/Interactable.meta
  Assets/Student/JWJ/Scripts/Interactable/Box.meta
  Assets/Student/JWJ/Scripts/Interactable/Box/Box Animator.controller
  Assets/Student/JWJ/Scripts/Interactable/Box/Box Animator.controller.meta
  Assets/Student/JWJ/Scripts/Interactable/Box/Box.cs
  Assets/Student/JWJ/Scripts/Interactable/Box/Box.cs.meta
  Assets/Student/JWJ/Scripts/Interactable/Box/BoxClosed.anim
  Assets/Student/JWJ/Scripts/Interactable/Box/BoxClosed.anim.meta
  Assets/Student/JWJ/Scripts/Interactable/Box/BoxOpen.anim
  Assets/Student/JWJ/Scripts/Interactable/Box/BoxOpen.anim.meta
  Assets/Student/JWJ/Scripts/Interactable/Portal.meta
  Assets/Student/JWJ/Scripts/Interactable/Portal/Portal.cs
  Assets/Student/JWJ/Scripts/Interactable/Portal/Portal.cs.meta
  Assets/Student/JWJ/TileMap.meta
  Assets/Student/JWJ/TileMap/Box.prefab
  Assets/Student/JWJ/TileMap/Box.prefab.meta
  Assets/Student/JWJ/TileMap/New Animated Tile.asset
  Assets/Student/JWJ/TileMap/New Animated Tile.asset.meta
Labels: Merge, Feat

#71 [Edit] 포탈 스폰
  Assets/Student/JWJ/Prefabs/Portal.prefab
  Assets/Student/JWJ/Scenes/TestScene_JWJ.unity
  Assets/Student/JWJ/Scripts/MonsterSpawner/MonsterSpawnTrigger.cs
Labels: Edit, Merge

#72 [Feat] BaseUI, TitleScene Setting
  Assets/Student/JHT/Scene.meta
  Assets/Student/JHT/Scene/TitleScene.unity
  Assets/Student/JHT/Scene/TitleScene.unity.meta
  Assets/Student/JHT/Scripts/UI.meta
  Assets/Student/JHT/Scripts/UI/BaseUI.cs
  Assets/Student/JHT/Scripts/UI/BaseUI.cs.meta
  Assets/Student/JHT/Scripts/UI/PointHandler.cs
  Assets/Student/JHT/Scripts/UI/PointHandler.cs.meta
  Assets/Student/JHT/Scripts/UI/PressSpaceButton.cs
  Assets/Student/JHT/Scripts/UI/PressSpaceButton.cs.meta
  Assets/Student/JHT/Scripts/UI/TitleCanvas.cs
  Assets/Student/JHT/Scripts/UI/TitleCanvas.cs.meta
  Assets/Student/JHT/Scripts/Weapon.meta
  Assets/Student/JHT/Scripts/Weapon/Flute.cs
  Assets/Student/JHT/Scripts/Weapon/Flute.cs.meta
  Assets/Student/JHT/Scripts/Weapon/FluteProjectile.cs
  Assets/Student/JHT/Scripts/Weapon/FluteProjectile.cs.meta
  Assets/Student/JHT/Scripts/Weapon/ViolinProjectile.cs
  Assets/Student/JHT/Scripts/Weapon/ViolinProjectile.cs.meta
Labels: Merge, Feat

#81 [Feat] Violin Ray, test Coin
  Assets/Scripts/Projectile/Projectile.cs
  Assets/Scripts/Projectile/ViolinProjectile.cs
  Assets/Student/JHT/JHT_Prototype.unity
  Assets/Student/JHT/Scripts/Coin.meta
  Assets/Student/JHT/Scripts/Coin/JHT_TestCoin.cs
  Assets/Student/JHT/Scripts/Coin/JHT_TestCoin.cs.meta
Labels: Merge, Feat

#86 [Feat] UseItem 수정
  Assets/Student/HSD/Prefabs/BossCirclePattern.prefab
  Assets/Student/HSD/Prefabs/BossLinePattern.prefab
  Assets/Student/HSD/Scripts/UseItem/UseItem.cs
Labels: Edit, Merge

#87 [feat]상자 아이템 정보 UI 구현
  Assets/Scripts/Interactable/Box/Box.cs
  Assets/Scripts/Interactable/Box/BoxRewardUI.cs
  Assets/Scripts/Interactable/Box/BoxRewardUI.cs.meta
  Assets/Scripts/Interactable/Box/BoxUI/BoxAnimator.controller
  Assets/Scripts/Interactable/Box/BoxUI/BoxAnimator.controller.meta
  Assets/Scripts/Interactable/Box/BoxUI/BoxUIiIn.anim
  Assets/Scripts/Interactable/Box/BoxUI/BoxUIiIn.anim.meta
  Assets/Scripts/Interactable/Box/BoxUI/BoxUiOut.anim
  Assets/Scripts/Interactable/Box/BoxUI/BoxUiOut.anim.meta
  Assets/Scripts/Item/Item.cs
  Assets/Student/JWJ/Scenes/JWJ_TestScene.unity
  Assets/Student/JWJ/Scenes/JWJ_TestScene.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes.meta
  Assets/Student/JWJ/Scenes/OldScenes/JWJ.unity
  Assets/Student/JWJ/Scenes/OldScenes/JWJ.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Prototype.unity
  Assets/Student/JWJ/Scenes/OldScenes/Prototype.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage1_1.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage1_1.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage1_2.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage1_2.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage1_3.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage1_3.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage2_1.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage2_1.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage2_2.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage2_2.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage2_3.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage2_3.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage3_1.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage3_1.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage3_2.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage3_2.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/Stage3_3.unity
  Assets/Student/JWJ/Scenes/OldScenes/Stage3_3.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/TestScene.unity
  Assets/Student/JWJ/Scenes/OldScenes/TestScene.unity.meta
  Assets/Student/JWJ/Scenes/OldScenes/TestScene_JWJ.unity
  Assets/Student/JWJ/Scenes/OldScenes/TestScene_JWJ.unity.meta
  Assets/Student/JWJ/TestItems.meta
  Assets/Student/JWJ/TestItems/New Item 1.asset
  Assets/Student/JWJ/TestItems/New Item 1.asset.meta
  Assets/Student/JWJ/TestItems/New Item 2.asset
  Assets/Student/JWJ/TestItems/New Item 2.asset.meta
  Assets/Student/JWJ/TestItems/New Item 3.asset
  Assets/Student/JWJ/TestItems/New Item 3.asset.meta
  Assets/Student/JWJ/TestItems/New Item 4.asset
  Assets/Student/JWJ/TestItems/New Item 4.asset.meta
  Assets/Student/JWJ/TestItems/New Item 5.asset
  Assets/Student/JWJ/TestItems/New Item 5.asset.meta
  Assets/Student/JWJ/TestItems/New Item 6.asset
  Assets/Student/JWJ/TestItems/New Item 6.asset.meta
  Assets/Student/JWJ/TestItems/New Item 7.asset
  Assets/Student/JWJ/TestItems/New Item 7.asset.meta
  Assets/Student/JWJ/TestItems/numbers.png
  Assets/Student/JWJ/TestItems/numbers.png.meta
Labels: Merge, Feat

#92 [Feat] ExplosionMonster
  Assets/Prefabs/MonsterPrefabs/NEW/ExplosionMonster.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/ExplosionMonster.prefab.meta
  Assets/Prefabs/MonsterPrefabs/NEW/MeleeMonster.prefab
  Assets/Prefabs/MonsterPrefabs/NEW/MeleeMonster.prefab.meta
  Assets/Scripts/Monster/FSM/BaseState.cs
  Assets/Scripts/Monster/FSM/SheetMusicMonsterFSM.cs
  Assets/Student/YTW/CircleRangeAnim.meta
  Assets/Student/YTW/CircleRangeAnim/Circle.prefab
  Assets/Student/YTW/CircleRangeAnim/Circle.prefab.meta
  Assets/Student/YTW/CircleRangeAnim/CircleRange.anim
  Assets/Student/YTW/CircleRangeAnim/CircleRange.anim.meta
  Assets/Student/YTW/CircleRangeAnim/CircleRangeAnim.controller
  Assets/Student/YTW/CircleRangeAnim/CircleRangeAnim.controller.meta
  Assets/Student/YTW/ExplosionAnim.meta
  Assets/Student/YTW/ExplosionAnim/Explosion.anim
  Assets/Student/YTW/ExplosionAnim/Explosion.anim.meta
  Assets/Student/YTW/ExplosionAnim/Explosion.controller
  Assets/Student/YTW/ExplosionAnim/Explosion.controller.meta
  Assets/Student/YTW/ExplosionAnim/Explosion.prefab
  Assets/Student/YTW/ExplosionAnim/Explosion.prefab.meta
  Assets/Student/YTW/ExplosionMonsterAnim.meta
  Assets/Student/YTW/ExplosionMonsterAnim/Attack.anim
  Assets/Student/YTW/ExplosionMonsterAnim/Attack.anim.meta
  Assets/Student/YTW/ExplosionMonsterAnim/Chase.anim
  Assets/Student/YTW/ExplosionMonsterAnim/Chase.anim.meta
  Assets/Student/YTW/ExplosionMonsterAnim/ExplosionMonster.controller
  Assets/Student/YTW/ExplosionMonsterAnim/ExplosionMonster.controller.meta
  Assets/Student/YTW/ExplosionMonsterAnim/Idle.anim
  Assets/Student/YTW/ExplosionMonsterAnim/Idle.anim.meta
  Assets/Student/YTW/ScriptableObj/ExplosionMonsterSO.asset
  Assets/Student/YTW/ScriptableObj/ExplosionMonsterSO.asset.meta
  Assets/Student/YTW/Scripts/ExplosionMonsterSO.cs
  Assets/Student/YTW/Scripts/ExplosionMonsterSO.cs.meta
  Assets/Student/YTW/Scripts/Monster/ExplosionIndicatorController.cs
  Assets/Student/YTW/Scripts/Monster/ExplosionIndicatorController.cs.meta
  Assets/Student/YTW/Scripts/Monster/ExplosionMonsterFSM.cs
  Assets/Student/YTW/Scripts/Monster/ExplosionMonsterFSM.cs.meta
  Assets/Student/YTW/TestScene.unity
Labels: Merge, Feat
